version: '2'
services:
  neo4j-server:
    image: neo4j:latest
    expose:
    - &bolt-port 7687
    - &http-port 7474
    - &https-port 7473
    ports:
    - 7687:7687
    - 7474:7474
    - 7473:7473
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_connector_bolt_listen__address: ":7687"
      NEO4J_dbms_connector_http_listen__address: ":7474"
      NEO4J_dbms_connector_https_listen__address: ":7473"
      #NEO4J_dbms_connectors_default__listen__address: "::"
    volumes:
    - /tmp/neo4j/conf:/conf

  seabolt-ci:
    depends_on: [neo4j-server]
    command: ./run_tests.sh
    build:
      context: .
      dockerfile: ./ci/linux/Dockerfile.build
    environment:
      BOLT_PORT: 7687
      BOLT_USER: neo4j
      BOLT_HOST: neo4j-server
      PASSWORD: password
      HAVE_SERVER: "yes"
      CHECK_SERVER_SLEEP: 15
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
